### ISSUE TITLE
组件内div上的style也会被rename成rootStyle

### ISSUE THREAD

**Issue by Ifeinstein** [ant-design/codemod-v5#48]
![image](https://user-images.githubusercontent.com/15973973/212227811-9f820501-47be-4e4d-ac9a-8192452ff210.png)

**Comment by Ifeinstein** [comment]
全局文件用正则 (<(?!Drawer)([^>]*\n)*.* )root(\w) 替换一下 $1\L$3， 源码实在不好读

**Comment by vagusX** [comment]
fixed in v1.1.5

**Comment by zdegoq01** [comment]
> 
希望 v1.1.5发个版本，因为现在 npm 上还是 1.1.4 的版本，所以执行 npx 之后，还是会有这个问题

**Comment by vagusX** [comment]
sorry but + @ant-design/codemod-v5@1.1.5
