### ISSUE TITLE
div上的className 也被转换成rootClassName了

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/codemod-v5#57]
理论上，只有Drawer中的className才应该被转换成rootClassName，结果发现，Drawer里面有children时，children中多有元素的className 都被转换成rootClassName了
`<Drawer
      mask={false}
      destroyOnClose
      open={visible}
      onClose={() => {
        setVisible(false);
      }}
      closable={false}
      placement="bottom"
      getContainer={false}
      rootClassName={Style.Drawer}
      height={168}
    >
      <div rootClassName={Style.CloseWrap}>
        <div rootClassName={Style.CloseContainer}>
          <div rootClassName={Style.CloseMask}>
            <div
              tabIndex={0}
              role="button"
              onClick={() => {
                setVisible(false);
              }}
              onKeyDown={() => {}}
              rootClassName={Style.Close}
            >
              <div rootClassName={Style.Plus}>+</div>
            </div>
          </div>
        </div>
      </div>
      <div rootClassName={Style.Root}>
        {map(item => (
          <File
            {...item}
            key={prop('type')(item)}
            onClick={() => {
              if (prop('canEdit')(item)) {
                push(
                  `/${getFeatureBy('link')(STAGING_CALCULATION)}/pay-approve/${prop('type')(
                    item,
                  )}/${currentPayApproveId}`,
                );
              } else {
                message.warning(`请先完成${prop('preTableName')(item)}`);
              }
            }}
          />
        ))(fileList)}
      </div>
    </Drawer>`

**Comment by dengfuping** [comment]
Fixed by #56. But `v1.1.5` is not published to npm and it's not working for now.

**Comment by vagusX** [comment]
sorry but + @ant-design/codemod-v5@1.1.5
